### ISSUE TITLE
Spread: Actions are not trigger if they are added to `options`

### ISSUE THREAD

**Issue by dafortin** [ciena-frost/ember-frost-core#332]

**Comment by sglanzer-fire** [comment]
@quincyle mentioned later in the day that this isn't a spread issue as much as a documentation issue - actions passed to the options need to be closures.  We could potentially provide a closure utility, but I think we should be fine just using `.bind(this)` - @quincyle correct me if that isn't sufficient - otherwise we'll document it

**Comment by sglanzer-fire** [comment]
This goes along with an accompanying change in ember-spread https://github.com/ciena-blueplanet/ember-spread/commit/a7a7118fdcbabbf79ced84f51eea7d8f9435d060

**Comment by sglanzer-fire** [comment]
Not an issue with `core` - will be handled in documentation against spread
