### ISSUE TITLE
Can't clear the text in a text box with `x`

### ISSUE THREAD

**Issue by vesper2000** [ciena-frost/ember-frost-core#484]
When the entered text is very long and the user wants to clear it, clicking on `x` does not always work.  Seems like the user needs to click on the top portion of it to make it work.

**Comment by notmessenger** [comment]
This is scheduled for resolution by 30 Apr 2018

**Comment by notmessenger** [comment]
@vesper2000 Can you please confirm that problem described in this issue still exists?  If it does can you please provide the steps that I can use to recreate it?   I ask because I have not been able to replicate this behavior.  I have attached a recording of my attempts to do so.

![ember-frost-core-issue-484](https://user-images.githubusercontent.com/435544/35056940-fe85e2d6-fb78-11e7-8eeb-8a8d2545f74c.gif)

**Comment by notmessenger** [comment]
I'm trying to make a better gif from my .mov or just reach out to me for it :-)

**Comment by notmessenger** [comment]
@vesper2000 please see this comment: https://github.com/ciena-frost/ember-frost-core/issues/484#issuecomment-358378359

**Comment by notmessenger** [comment]
@vesper2000 has confirmed that this is no longer an issue.

**Comment by notmessenger** [comment]
@vesper2000 Here is a better screen capture of my attempt to recreate this issue.  I pulled down the latest `master` of this repo, ran `ember s`, and recorded the video.

https://youtu.be/WHb7RWQgTdc

If you do the same are you experiencing the reported issue or is it occurring within an application?  Slack is still down so can wait to schedule a zoom or invite via calendar if prefer.

UPDATE: The video I posted does not demonstrate more than 255 characters being entered, as reported in the JIRA story, but when tested with this length the same behavior occurs.
